name: PHP Compatibility

permissions:
  contents: read

on:
  push

jobs:
  phpcompatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: PHPCompatibility
        uses: pantheon-systems/phpcompatibility-action@7bf1b2881e207c80ad4569874ceee225f59537d1 # v1.1.1
        with:
          test-versions: 7.4-
  checkdeprecations:
    runs-on: ubuntu-latest
    name: Check for deprecations
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: 8.4
      - name: Check for deprecations
        run: |
          composer install
          composer run check-deprecations
